services:
  securemailscope:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securemailscope
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
